README.md

This small PR changes the link to the samples on the main README file. Instead of using an absolute path, this uses a relative path to the base folder. 
Note the previous link was initially valid, but was broken as part of a file rename int the bicep examples.

Updating example link to be a relative path

---

.devcontainer/devcontainer.json
.vscode/launch.json
BenchPress/Helpers/Azure/BenchPress.Azure.psd1
BenchPress/Helpers/Azure/Bicep.psm1
examples/actionGroupErrors.bicep

Updated the devcontainer to use an image that supports .NET 6.0 so that Generators builds.
Added launch configurations for PowerShell debugging (these still aren't quite right). Added a bicep file that has errors that will manifest during `bicep build`. Added the Confirm-BicepFile cmdlet for validating bicep files against `bicep build`. Added Confirm-BicepFile to the PS Module manifest.

#43 Create bicep helper

---

.github/config/linter/PSScriptAnalyzerSettings.psd1
BenchPress/Helpers/Azure/AzureCli.psm1
BenchPress/Helpers/Azure/Bicep.psm1

As discussed in design session, longterm suppression of PowerShell linting rules will be moved to function level rather than global level
- Global suppression removed from PSScriptAnalyzer configuration
- Suppression added as cmdlet binding to appropriate functoins
- Casing of parameter name addressed as a result of the above bullet

Scope PowerShell linting suppression to a function scope rather than global

---

.github/workflows/ci.yml

- `working-directory` cannot be used when using an action
- full path for archival is moved to the `with` keyword

Bugfix: Working Directory keyword cannot be used with an action

---

.github/workflows/ci.yml

Executing Install-Module Az as a dependency of executing unit tests.

#116 Bug: Install Az Module as part of the CI flow for PowerShell Unit Tests

---

.github/workflows/ci.yml
.github/workflows/pr-dotnet.yml
.github/workflows/pr-powershell.yml

Shifting unit tests per this [issue](https://github.com/Azure/benchpress/issues/112).
I moved everything out of` ci.yml` to `pr.powershell.yml` since there were only PowerShell unit tests in there.
Don't think we need the archive step since it won't go to CD, but kept in there nonetheless. Open to deleting it.

Move unit tests

---

.github/workflows/cd-github-release.yml

Fixed the CD Release trigger to correctly only trigger when the version tag has been pushed and the branch it was pushed to is the main branch.
Closes #132

#132 GH release executes at incorrect event.

---

BenchPress/Generators/ResourceTypes/ResourceType.cs
BenchPress/Generators/TestMetadata.cs

Updated the ResourceType.cs file to fix the linting issues.
Minor refactor of TestMetadata.cs to keep the return type consistent for ResourceType.cs.
Closes #99

#99 Resolve .NET Linter Issues

---

BenchPress/Helpers/BenchPress.Azure/BenchPress.Azure.psd1
BenchPress/Helpers/BenchPress.Azure/Common.Tests.ps1
BenchPress/Helpers/BenchPress.Azure/Common.psm1
examples/Common.Tests.ps1

Includes the PoC code that was shown during design session with unit tests and examples introduced.
- Kept the `Confirm-AzBPResource` name. After researching approved verbs, `Confirm` still made the most sense.
- `Confirm-AzBPResource` will handle checking whether a resource exists and also provides functionality checking a property on a resource is set to the correct value
As I was cleaning up my code and running further tests, there were some additional really interesting design questions that came up. They are reflected in #155 and #154. Since these design questions would greatly affect the implementation of `Confirm-AzBPResource`, I understand if we would want to hold off on merging this until we get a better idea of how to proceed on those two design questions.

Confirm-AzBPResource Initial Implementation

---

docs/getting_started.md
examples/AKSCluster.Tests.ps1
examples/ActionGroup.Tests.ps1
examples/AppServicePlan.Tests.ps1
examples/ContainerRegistry.Tests.ps1
examples/KeyVault.Tests.ps1
examples/ResourceGroup.Tests.ps1
examples/SqlDatabase.Tests.ps1
examples/SqlServer.Tests.ps1
examples/VirtualMachine.Tests.ps1
examples/WebApp.Tests.ps1

With change to `Confirm-` resource, we don't need the exist functions anymore.
Updated `getting-started.md` with up-to-date function calls and errors

Remove dated functions and update getting-started.md

---

BenchPress/Helpers/BenchPress.Azure/Common.Tests.ps1
BenchPress/Helpers/BenchPress.Azure/Common.psm1
examples/Common.Tests.ps1

This PR addresses the discussion that came about on #162. It specifically addresses [this discussion](https://github.com/Azure/benchpress/pull/162#issuecomment-1440603361).
User's can now confirm properties if a property is stored in an array (i.e. access policies on a key vault). However, this approach does put the onus on the user to know the exact index to use.
Closes #165

Allow for ability to check properties that are stored in arrays

---

.github/workflows/ci.yml
Modules/BenchPress.Azure/BenchPress.Azure.psd1

Installing Az before running `Test-ModuleManifest` and before generating the docs.
Also added `Az` as an external dependency.

#196 Fix broken GitHub Actions from the structure refactor. (v2)

---

.github/workflows/ci.yml
.github/workflows/pr-powershell.yml
BenchPress/Generators/ResourceTypes/PortalDashboard.cs
Modules/BenchPress.Azure/BenchPress.Azure.psd1
Modules/BenchPress.Azure/Classes/ResourceType.psm1
Modules/BenchPress.Azure/Public/Confirm-PortalDashboard.ps1
Modules/BenchPress.Azure/Public/Get-ResourceByType.ps1
Modules/BenchPress.Azure/Tests/Public/Confirm-PortalDashboard.Tests.ps1
docs/getting_started.md
examples/Dashboard/Dashboard.Tests.ps1
examples/Dashboard/Dashboard_Example.md
examples/Dashboard/dashboard.bicep

Closes #260.
Note, Az.Portal module needs to be separately installed because it is not a part of the main Az Module. Following up with PG here: https://github.com/Azure/azure-powershell/issues/21363. Follow up issue to remove Az.Portal when it becomes GA: https://github.com/Azure/benchpress/issues/287.
Also note, the negative test throws an exception, so it has not been included as an example test.

Azure Dashboard Support

---

Modules/BenchPress.Azure/BenchPress.Azure.psd1
Modules/BenchPress.Azure/Classes/ResourceType.psm1
Modules/BenchPress.Azure/Public/Confirm-DiagnosticSetting.ps1
Modules/BenchPress.Azure/Public/Confirm-Resource.ps1
Modules/BenchPress.Azure/Public/Get-ResourceByType.ps1
Modules/BenchPress.Azure/Tests/Public/Confirm-DiagnosticSetting.Tests.ps1
examples/AppInsights/AppInsights.Tests.ps1
examples/AppInsights/AppInsights_Example.md
examples/AppInsights/appInsights.bicep

Added support for `Confirm-DiagnosticSetting` closing #258.
No negative test because it showed errors, even though they were all passing.
No location test because it failed.
No `.cs` file because I don't think you can get `resourceId` from the generated ARM template, but I'm going to link the code block from the JSON output below in case I missed something.
```JSON
{
{
"type": "Microsoft.Insights/diagnosticSettings",
"apiVersion": "2021-05-01-preview",
"scope": "[format('Microsoft.Insights/components/{0}', parameters('appInsightsName'))]",
"name": "default",
"properties": {
"workspaceId": "[resourceId('Microsoft.OperationalInsights/workspaces', parameters('workspaceName'))]",
"metrics": [
{
"category": "AllMetrics",
"enabled": true
}
]
},
"dependsOn": [ …
```

Add App Insights Diagnostic Settings Support

---

BenchPress/Generators/LanguageProviders/ILanguageProvider.cs
BenchPress/Generators/LanguageProviders/PowershellLanguageProvider.cs
BenchPress/Generators/Program.cs
BenchPress/Generators/ResourceTypes/ResourceType.cs
BenchPress/Generators/TestGenerator.cs
BenchPress/Generators/templates/powershell/template.ps1

- Changes generated test from:
```
$result = Confirm-AzBPResource @params
$result.Success | Should -Be $true
```
to:
```
Confirm-AzBPResource @params | Should -BeSuccessful
```
- Cleans up the Language Provider Interface and removes methods no longer needed
- Adds a `GetSupportedTestTypes` method to base `ResourceType` class for the possibility of generating different types of tests (e.g. -InLocation) per derived class in the future
Closes #305.

Generate `-BeSuccessful` Tests

---

Modules/BenchPress.Azure/Tests/Public/Get-ResourceByType.Tests.ps1

Closes #302
**Note:** This is in draft mode since I'm not sure if this is the approach we want to take.
- Iterate through the `ResourceType` enum and use it to determine the Powershell function name
- Dynamically determine test cases based on the `ResourceType` enum
- Add new `Get-ResourceByType` parameters to test

Test all resources in  Get-ResourceByType unit tests

---

.github/workflows/ci-module-versioning.yml

Adding workflow dispatch to Module Version workflow in order to allow maintainers to trigger workflow directly.

adding workflow_displatch to module versioning workflow

---

.github/workflows/cd-psgallery.yml

This PR adds a build-modules job to the workflow the releases to the PR gallery.

adding build-modules job to psgallery cd workflow

---

.github/workflows/cd-psgallery.yml

Adding a job dependency to ensure that publish only fires after build modules is complete.

adding job dependencies in ps gallery cd workflow

---

.github/workflows/ci.yml

Fixing the `ci.yml` PS Gallery import to import from the local PS Gallery.
Closes #332

#332 Update ci.yml to use the correct PS Gallery (local)

---

build.ps1

There is a discrepancy between the behavior and documentation for [build.ps1](https://github.com/Azure/benchpress/blob/main/build.ps1)
Documentation says;
> To clean the bin folder before outputting the artifacts from build.ps1 the -Clean flag can be passed.
But, when we run the following command;
```powershell
build.p1 -Clean
```
It cleans-up the `./bin` folder, then doesn't stop and creates the `.psd1` and `.psm1` files (just like `-Import` flag passed)
This PR ensures the script exits after cleanup, when `-Clean` flag provided

if -Clean flag provided, return from the script after cleanup

---

Modules/BenchPress.Azure/BenchPress.Azure.psd1
Modules/BenchPress.Azure/Private/Connect-Account.ps1
Modules/BenchPress.Azure/Private/Get-EnvironmentVariable.ps1
Modules/BenchPress.Azure/Tests/Private/Connect-Account.Tests.ps1
Modules/BenchPress.Azure/Tests/Public/Get-ResourceByType.Tests.ps1
assets/demos/main.bicep
examples/AksCluster/aksCluster.bicep
examples/ApiManagement/ApiManagement.bicep
examples/AppInsights/appInsights.bicep
examples/AppServicePlan/appServicePlan.bicep
examples/ContainerApp/containerApp.bicep
examples/CosmosDB/cosmosDB.bicep
examples/Dashboard/dashboard.bicep
examples/DataFactory/dataFactory.bicep
examples/EventHub/eventHub.bicep
examples/KeyVault/keyVault.bicep
examples/OperationalInsightsWorkspace/operationalInsightsWorkspace.bicep
examples/PostgreSql/postgresql.bicep
examples/ResourceGroup/ResourceGroup.Tests.ps1
examples/ResourceGroup/resourceGroup.bicep
examples/SQL/sql.bicep
examples/SearchService/SearchService.bicep
examples/Storage/storage.bicep
examples/Synapse/synapse.bicep
examples/WebApp/webApp.bicep

This change affects the auth mechanism and specifically introduces the following:
- If Az.Powershell is connected, skip all auth and use existing connection. This also removes the need to set environment variables if the connection is existing.
- If environment variables are set, check that subscription id, tenant ip and application id match the current context, if not, throw an error.
- Remove the need to specify a subscription id for managed identities. It can still be passed it as optional if there is a specific subscription that needs to be used.

Auth updates
