Azure/benchpress

.devcontainer/devcontainer.json
=> improving-codespace-definition

BenchPress/Helpers/Azure/ContainerRegistry.psm1, examples/ContainerRegistry.Tests.ps1, examples/containerRegistry.bicep
=> creating container registry module and sample tests

BenchPress/Helpers/Azure/AKSCluster.psm1, BenchPress/Helpers/Azure/BenchPress.Azure.psd1, examples/AKSCluster.Tests.ps1, examples/aksCluster.bicep
AKS Cluster module
Here is the sample executions;
`Verify AKS Cluster Exists` :
`Spin up , Tear down AKS Cluster` :
=> aks-cluster-module

BenchPress/Helpers/Azure/ActionGroup.psm1, examples/ActionGroup.Tests.ps1, examples/actionGroup.bicep
closes #80
initial helper module for azure action groups
=> creating initial action group module

.github/workflows/publish-docs.yml
=> creating initial pipeline to auto generate docs

CHANGELOG.md, ROADMAP.md
adding initial CHANGELOG and ROADMAP documents
in every release we'll update the CHANGELOG, with, what changes are made, and features included within the release
in every six months (could be shorter or longer), we'll update the ROADMAP, with, what changes are made in the next releases
=> Admin Chores

BenchPress/Helpers/Azure/BenchPress.Azure.psd1, BenchPress/Helpers/Azure/KeyVault.psm1, examples/KeyVault.Tests.ps1, examples/keyVault.bicep
closes #27 
initial helper module for azure keyvault, keyvault keys, keyvault secrets, keyvault certificates
added helpers;
- Get-KeyVault
- Get-KeyVaultExists
- Get-KeyVaultSecret
- Get-KeyVaultSecretExists
- Get-KeyVaultKey
- Get-KeyVaultKeyExists
- Get-KeyVaultCertificate
- Get-KeyVaultCertificateExists
=> create keyvault helpers

BenchPress/Helpers/Azure/Common.Tests.ps1, BenchPress/Helpers/Azure/Common.psm1, BenchPress/Helpers/Azure/SqlDatabase.psm1
Added unit tests for the Common module.
Updated the Common module to address issues discovered with the new unit tests.
Updated the SqlDatabase module to address issues discoverd with the new unit tests.
=> #67 Create initial unit test for CI pipeline

examples/AKSCluster.Tests.ps1, examples/ActionGroup.Tests.ps1, examples/Common.Tests.ps1, examples/ContainerRegistry.Tests.ps1, examples/KeyVault.Tests.ps1, examples/ResourceGroup.Tests.ps1
closes #100 
Powershell scripts in ./examples folder imports main BenchPress module `./BenchPress/Helpers/Azure/BenchPress.Azure.psd1` instead of importing sub-modules separately.
=> updating powershell example scripts

.github/workflows/cd-github-release.yml, .github/workflows/cd-psgallery.yml
Added workflows for a GitHub (pre)release and for a PSGallery production release.
I used the same GitHub release action that was used in DeployFeatures.yml.
=> #85 Create CD Pipeline

BenchPress/Helpers/Azure/AKSCluster.psm1, BenchPress/Helpers/Azure/ActionGroup.psm1, BenchPress/Helpers/Azure/AppServicePlan.psm1, BenchPress/Helpers/Azure/AzureCli.psm1, BenchPress/Helpers/Azure/Bicep.psm1, BenchPress/Helpers/Azure/Common.psm1, BenchPress/Helpers/Azure/ContainerRegistry.psm1, BenchPress/Helpers/Azure/KeyVault.psm1, BenchPress/Helpers/Azure/ResourceGroup.psm1, BenchPress/Helpers/Azure/SqlDatabase.psm1, BenchPress/Helpers/Azure/SqlServer.psm1, BenchPress/Helpers/Azure/VirtualMachine.psm1, BenchPress/Helpers/Azure/WebApp.psm1, examples/AKSCluster.Tests.ps1, examples/ActionGroup.Tests.ps1, examples/ContainerRegistry.Tests.ps1, examples/KeyVault.Tests.ps1, examples/ResourceGroup.Tests.ps1
- Help comments for all existing cmdlets
- As a result, updated the parameters for Remove-BicepFeature and Deploy-BicepFeature to match the rest of the cmdlets and files in the `examples` folder were updated to reflect these changes
Closes #92
=> Help Comments for Existing Cmdlets

README.md, docs/getting_started.md, examples/AKSCluster.Tests.ps1, examples/ActionGroup.Tests.ps1, examples/Common.Tests.ps1, examples/ContainerRegistry.Tests.ps1, examples/KeyVault.Tests.ps1, examples/ResourceGroup.Tests.ps1
This PR introduces a getting started document that walks a user through one of the basic examples in the `examples` folder
Closes #22
=> Getting Started Documentation

CONTRIBUTING.md
Added the CONTRIBUTING.md file.
NOTE: I added a Contributor License Agreement section that mirrors those found with Microsoft open-source projects. It mentions a "bot". I have no idea what this bot is, but we should probably use it!
=> #120 Contribution documentation

docs/ci_cd_workflows.md
Document that goes over our CI/CD system and a high-level description of the various workflows that execute within the larger system.
Closes #121 - Regarding the second point in that Issue, terratest's best practices are very specific to terraform so could not repurpose them. Since we may be doing some redesigning the end-user experience, it may be best to do a "best practices" doc after design changes are in place.
=> "Architecture" Doc for Various Workflows

docs/installation.md
Added the installation documentation.
=> #124 Installation Guide

CONTRIBUTING.md
Added local environment setup to CONTRIBUTING.md.
Closes #119
=> #119 Local dev environment documentation

BenchPress/Helpers/BenchPress.Azure/Authentication.Tests.ps1, BenchPress/Helpers/BenchPress.Azure/Authentication.psm1, BenchPress/Helpers/BenchPress.Azure/BenchPress.Azure.psd1, docs/getting_started.md
Adding the authentication module.
=> #145 Create Authentication Module

BenchPress/Helpers/BenchPress.Azure/Authentication.psm1
- Wanted to clarify 'module' in the auth functions
=> Small documentation addition

.gitignore, BenchPress/Helpers/BenchPress.Azure/AKSCluster.Tests.ps1, BenchPress/Helpers/BenchPress.Azure/AKSCluster.psm1, BenchPress/Helpers/BenchPress.Azure/ActionGroup.Tests.ps1, BenchPress/Helpers/BenchPress.Azure/ActionGroup.psm1, BenchPress/Helpers/BenchPress.Azure/AppServicePlan.Tests.ps1, BenchPress/Helpers/BenchPress.Azure/AppServicePlan.psm1, BenchPress/Helpers/BenchPress.Azure/Bicep.Tests.ps1, BenchPress/Helpers/BenchPress.Azure/Bicep.psm1, BenchPress/Helpers/BenchPress.Azure/Common.Tests.ps1, BenchPress/Helpers/BenchPress.Azure/Common.psm1, BenchPress/Helpers/BenchPress.Azure/ContainerRegistry.Tests.ps1, BenchPress/Helpers/BenchPress.Azure/ContainerRegistry.psm1, BenchPress/Helpers/BenchPress.Azure/KeyVault.Tests.ps1, BenchPress/Helpers/BenchPress.Azure/KeyVault.psm1, BenchPress/Helpers/BenchPress.Azure/ResourceGroup.Tests.ps1, BenchPress/Helpers/BenchPress.Azure/ResourceGroup.psm1, BenchPress/Helpers/BenchPress.Azure/SqlDatabase.Tests.ps1, BenchPress/Helpers/BenchPress.Azure/SqlDatabase.psm1, BenchPress/Helpers/BenchPress.Azure/SqlServer.Tests.ps1, BenchPress/Helpers/BenchPress.Azure/SqlServer.psm1, BenchPress/Helpers/BenchPress.Azure/VirtualMachine.Tests.ps1, BenchPress/Helpers/BenchPress.Azure/VirtualMachine.psm1, BenchPress/Helpers/BenchPress.Azure/WebApp.Tests.ps1, BenchPress/Helpers/BenchPress.Azure/WebApp.psm1, docs/getting_started.md, examples/ResourceGroup.Tests.ps1
Adding authentication `Connect-Account` to each Get-Resource.
Added additional information about using environment variables in the `getting_started.md`.
=> #151 Wire up authentication module

examples/AKSCluster.Tests.ps1, examples/ActionGroup.Tests.ps1, examples/AppServicePlan.Tests.ps1, examples/Common.Tests.ps1, examples/ContainerRegistry.Tests.ps1, examples/KeyVault.Tests.ps1, examples/ResourceGroup.Tests.ps1, examples/SqlDatabase.Tests.ps1, examples/SqlServer.Tests.ps1, examples/VirtualMachine.Tests.ps1, examples/WebApp.Tests.ps1
Title
If you want to learn more about using `ErrorAction`, [here ](http://web.archive.org/web/20220324133408/https://devops-collective-inc.gitbook.io/the-big-book-of-powershell-error-handling/controlling-error-reporting-behavior-and-intercepting-errors)is a good resouce.
=> Adding sample negative tests with suppressed errors

.github/workflows/ci.yml
Not sure why this started failing for not having platyPS installed and imported, but moved the commands to a single pwsh session.
=> #196 Fix broken GitHub Actions from the structure refactor.

Modules/BenchPress.Azure/BenchPress.Azure.psd1, Modules/BenchPress.Azure/Public/Confirm-OperationalInsightsWorkspace.ps1, Modules/BenchPress.Azure/Public/Confirm-Resource.ps1, Modules/BenchPress.Azure/Public/Get-ResourceByType.ps1, Modules/BenchPress.Azure/Tests/Public/Confirm-OperationalInsightsWorkspace.Tests.ps1, examples/OperationalInsightsWorkspace/OperationalInsightsWorkspace.Tests.ps1, examples/OperationalInsightsWorkspace/OperationalInsightsWorkspace_Example.md, examples/OperationalInsightsWorkspace/operationalInsightsWorkspace.bicep
Added Operational Insights Workspace cmdlets, tests, and examples.
Closes #174
=> #174 Log Analytics support

Modules/BenchPress.Azure/BenchPress.Azure.psd1, Modules/BenchPress.Azure/Public/Confirm-Resource.ps1, Modules/BenchPress.Azure/Public/Confirm-StorageAccount.ps1, Modules/BenchPress.Azure/Public/Get-ResourceByType.ps1, Modules/BenchPress.Azure/Tests/Public/Confirm-StorageAccount.Tests.ps1, examples/StorageAccount/StorageAccount.Tests.ps1, examples/StorageAccount/StorageAccount_Example.md, examples/StorageAccount/storageAccount.bicep
=> create storage account module

Modules/BenchPress.Azure/Public/CustomAssertions/BeInResourceGroup.ps1, Modules/BenchPress.Azure/Tests/Public/CustomAssertions/BeInResourceGroup.Tests.ps1, examples/StorageAccount/StorageAccount.Tests.ps1, examples/StorageAccount/storageAccount.bicep, examples/Synapse/Synapse.Tests.ps1, examples/Synapse/Synapse_Example.md
- Added example tests for storage account using custom assertions.
- Added support for getting resource group information using `Id` property. This adds support for Synapse resources.
=> Support for ResourceGroup Custom Assertion Using Id

.github/workflows/ci-module-versioning.yml, .github/workflows/ci.yml, docs/ci_cd_workflows.md
Title says it all :)
Closes #225
=> Remove automated prs from workflows and update doc

.github/workflows/ci.yml, .github/workflows/pr-powershell.yml, Modules/BenchPress.Azure/BenchPress.Azure.psd1, Modules/BenchPress.Azure/Classes/ResourceType.psm1, Modules/BenchPress.Azure/Public/Confirm-ContainerApp.ps1, Modules/BenchPress.Azure/Public/Get-ResourceByType.ps1, Modules/BenchPress.Azure/Tests/Public/Confirm-ContainerApp.Tests.ps1, docs/getting_started.md, examples/ContainerApp/ContainerApp.Tests.ps1, examples/ContainerApp/ContainerApp_Example.md, examples/ContainerApp/containerApp.bicep
Support for container application. Closes #252.
=> Container Application Support

BenchPress/README.md, assets/demos/DemoApp.Tests.ps1, assets/demos/README.md, assets/demos/deploy-demoapp.ps1
=> Update canonical app to use Confirm-AzBPResource

CONTRIBUTING.md
=> Add Resource Type condition to contribution docs

examples/ResourceGroup/resourceGroup.bicep, examples/Storage/storage.bicep, examples/Synapse/synapse.bicep
I have confirmed that the resources deploy and that the tests pass.
Closes #296
=> #296 Updated outdated versions in the bicep files.

BenchPress/Generators/ResourceTypes/WebAppStaticSite.cs, Modules/BenchPress.Azure/BenchPress.Azure.psd1, Modules/BenchPress.Azure/Classes/ResourceType.psm1, Modules/BenchPress.Azure/Public/Confirm-WebAppStaticSite.ps1, Modules/BenchPress.Azure/Public/Get-ResourceByType.ps1, Modules/BenchPress.Azure/Tests/Public/Confirm-WebAppStaticSite.Tests.ps1, examples/WebApp/WebApp.Tests.ps1, examples/WebApp/WebApp_Example.md, examples/WebApp/webApp.bicep
=> Add support for static web app and an example of verifying web app config

CONTRIBUTING.md
Added additional information for a code contributor.
If you can think of any new items to add, I think the best course of action is to pull the branch add your updates and then push them back to the repo.
Closes #303
=> #303 Ensure contributor's Read Me includes instructions for adding examples.

BenchPress/Generators/AzureDeploymentImporter.cs, BenchPress/Generators/TestMetadata.cs
Updated the `GetExtraProperties` method to iterate over the array of `DependsOn` to extract all keys and values.
Closes #312
=> #312 Iterate through dependsOn when creating extraProperties dictionary in Generator code

examples/CosmosDB/cosmosDB.bicep, examples/PostgreSql/PostgreSql.Tests.ps1, examples/PostgreSql/postgresql.bicep
Updated the PostgreSQL bicep file and tests.
Note that the negative tests throws an exception.
Closes #338
=> #338 Update PostgreSQL Flexible Server Version

.github/workflows/ci.yml, .github/workflows/pr-powershell.yml, Modules/BenchPress.Azure/BenchPress.Azure.psd1, Modules/BenchPress.Azure/Classes/ResourceType.psm1, Modules/BenchPress.Azure/Public/Confirm-SearchService.ps1, Modules/BenchPress.Azure/Public/Get-ResourceByType.ps1, Modules/BenchPress.Azure/Tests/Public/Confirm-SearchService.Tests.ps1, examples/SearchService/SearchService.Tests.ps1, examples/SearchService/SearchService.bicep, examples/SearchService/SearchService_Example.md
Adding support for `Azure Search Service`
You can find the screenshot of running the tests locally;
=> adding search service module

.devcontainer/devcontainer.json, .vscode/extensions.json
updating codespaces configuration to latest version
syncing recommended vscode extensions with extensions installed in codespaces
=> updating codespace vscode configuration
